version: '2'

services:
  nginx:
    network_mode: bridge
    image: "nginx:alpine"
    ports:
      - 80:80
    links:
      - schnoeselclub:schnoeselclub
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  schnoeselclub:
    network_mode: bridge
    image: "vm-registry.sandbox.lan/fkleine/schnoeselclub:2.0"
    ports:
      - 127.0.0.1:3000:3000
